name: libportal
buildsystem: meson
builddir: true
config-opts:
  - "-Dbackends=gtk3"
  - "-Ddocs=false"
sources:
  - type: archive
    url: https://github.com/resurrecting-open-source-projects/scrot/archive/refs/tags/1.7.tar.gz
    sha256: d8c8cb18a34e5eeb26a39c94044c955995b01de0e139caac5e18c076cf821b3b
